server:
  port: 9998

datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://sorakaze.duckdns.org:3336/ufc?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
  username: root
  password: scit123$
jpa:
  hibernate:
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    ddl-auto: none
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true


flask:
  api:
    url: http://localhost:5000
